version: '3'
services:
  web_monitor:
    build: .
    ports: 
      - "8888:29000"
    volumes:
      - ~/SpaceDefenceService/Config:/SpaceDefenceService/Config
      - ~/SpaceDefenceService/Logs:/SpaceDefenceService/Logs
      - ~/SpaceDefenceService/Monitor:/SpaceDefenceService/Monitor
